import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "../globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const optima = localFont({
  src: [
    {
      path: "../fonts/Optima/OPTIMA.TTF",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/Optima/Optima_Italic.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "../fonts/Optima/Optima Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../fonts/Optima/OPTIMA_B.TTF",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-optima",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${optima.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
